CREATE SEQUENCE main_seq;

CREATE TABLE TST_MAIN
    (
        ID BIGINT PRIMARY KEY,
        MAIN_NAME VARCHAR(256) NOT NULL,
        MAIN_DESCRIPTION VARCHAR(1000)
    );

create unique index IDX_MAIN_UNIQUE on TST_MAIN(MAIN_NAME);